### ISSUE TITLE
Lost the Minimap Icon

### ISSUE THREAD

**Issue by Pama123** [kakysha/HonorSpy#10]
I have missclicked the minimap icon and now its gone.

If I try to get it back by: /hs standby i get an error: Interface\FrameXML\ChatFrame.lue:2170:AceConsole-2.0: AceConsole-2.0: Option handler "IsActive" not found.

Anything to solve that problem. Reinstalling does nothing.

**Comment by kakysha** [comment]
Delete `WTF\Account\YourName\SavedVariables\HonorSpy.lua` and `HonorSpy.lua.bak`
