### ISSUE TITLE
Feature Request: Estimated Honor Update & History

### ISSUE THREAD

**Issue by Medry** [kakysha/HonorSpy#100]
Would be extremely helpful for those of us stacking brackets to have the ability to see other players current estimated honor for the day. We're running into issues with people potentially going over cap for the week the day before reset and being unable to check. HonorSpy already seems to continuously share data throughout the day. Players seeking accuracy could still use the correct calculated value from the previous day.
Could add it as a new column, or create an entire new "tab" on the GUI. A drop-down selection would also be nice and allow for another feature that would help.
It would also be extremely helpful if it would save the data from the previous week and allow us to view it in the future. We had issues this week with someone breaking brackets, and we had to wait an entire 24 hours for the first honor calc of the week for the data to start coming in so we could see who it was.

I know reworking the GUI would probably be a pain in the ass, but any way we can track an individuals estimated honor for the week to know if they are breaking brackets or not would be a lifesaver

Great addon, appreciate the work put into it, Just a couple features (Mainly being able to see estimated) that would make it exceptional for trying to efficiently progress through this punishing honor system. 
Medry#2553 on discord if you ever want to chat, you're a tough guy to get in contact with!

Happy Holidays, 
Medry

**Comment by kakysha** [comment]
This is a big feature, which could be potentially used by small amount of players. I'm trying to keep addon as simple as possible. Also, if ppl breaking the brackets, they can modify one line in the code to not share their "estimated" honor by their addon.
