### ISSUE TITLE
Suggestion: Add an optional setting to reverse "Bracket Order"

### ISSUE THREAD

**Issue by pedro-cf** [kakysha/HonorSpy#102]
As title suggests.

A lot of people prefer naming the 14th bracket Bracket 1 and so on.

Consider making this a checkbox on the HonorSpy Interface Options.

**Comment by kakysha** [comment]
Thats incorrect naming, why should I adapt to those incorrect names? Brackets = Ranks, so Rank14 means you should be in BR14, not BR1.
