### ISSUE TITLE
Random players in my friendlist

### ISSUE THREAD

**Issue by ChekistNSK** [kakysha/HonorSpy#106]
Addon add some random players to my friendlist w/o any permission with comment "HonorSpy testing"... wtf?

**Comment by kakysha** [comment]
this is a process of checking for fakes. They are deleted immediately after being added. If they are not, its obviously a bug, and you should file a report.

**Comment by ChekistNSK** [comment]
What should i post, file a report... ? i have only screenshots and version of addon in 1.71 (updated via twitch).
![WoWScrnShot_123119_113952](https://user-images.githubusercontent.com/12393863/71610357-c0695600-2bc2-11ea-9e5f-8d65c632fb1a.jpg)
![WoWScrnShot_123119_113956](https://user-images.githubusercontent.com/12393863/71610360-c3fcdd00-2bc2-11ea-83c0-a2f143cc3300.jpg)

**Comment by ChekistNSK** [comment]
My guildies told me addon add random players in friend-list and does not remove it!

**Comment by ChekistNSK** [comment]
i delete addon because of no answer with bug.
