### ISSUE TITLE
还是更新时间问题。

### ISSUE THREAD

**Issue by tzn521** [kakysha/HonorSpy#108]
如图，实际更新时间早了1个小时，建议 中国服务器能加2小时。
As shown in the figure, the actual update time is 1 hour earlier. It is suggested that the Chinese server can add 2 hours.

![image](https://user-images.githubusercontent.com/42259435/71603087-41f6bf00-2b96-11ea-96cf-943afa9baee6.png)

再次感谢作者！非常感谢！

**Comment by Binkcn** [comment]
国服的荣誉更新时间我看了一下，比较随缘，没有一个准确的时间。
