### ISSUE TITLE
Request: display Honor / HK Ratio

### ISSUE THREAD

**Issue by c0mm0n** [kakysha/HonorSpy#109]
Hi,

i'm looking into people botting Honor in AV.
Seems one interesting metric is the Honor / HK ratio.

Most people are in the 100-170 area, while some people suspected of botting are way above 250 (lot of honor, but very low kills).

Would it be possible
1. add it in the character Honor pane? (data is there, it's just a new display)
2. add it in the main table? (do you already sync HKs atm?)

Hope it can be achieved, thx!

**Comment by rpbailey-dm** [comment]
This would be a great addition.

**Comment by kakysha** [comment]
It has nothing to do with the idea of HonorSpy
