### ISSUE TITLE
Change honorspy to check today's HKs and this week HKs

### ISSUE THREAD

**Issue by Streamsnipe** [kakysha/HonorSpy#111]
Currently Honorspy only checks to see if this week hks are > 15 before it adds a player to pool. But we can have it so that it also looks at todays hk's as a decider so the users don't have to wait 24 hours to see if a player is added into the pool.

Very easy 1 liner change.

**Comment by kakysha** [comment]
HonorSpy works the same as WoW servers do. Servers only look at "This Week ..." numbers, so does HonorSpy.

**Comment by Streamsnipe** [comment]
Yikes you are one dumb fuck. You can change this so that users broadcast their information sooner. Who gives a fuck what the servers do?

**Comment by towneh** [comment]
This is more bullshit that can be spoofed, keep it simple stupid.
