### ISSUE TITLE
[Minor] GUI.lua error

### ISSUE THREAD

**Issue by Sethox** [kakysha/HonorSpy#114]
There is a minor error in honorspy/GUI.lua:
it's
`local _, this_week_honor - GetPVPThisWeekStats();`
instad of
`local _, this_week_honor = GetPVPThisWeekStats();`

Thus solving the error that pops up.

Using git clone version.
Close issue when ready.

**Comment by zembtach** [comment]
I think you mean this line
https://github.com/kakysha/HonorSpy/blob/ba5cf143236b20e6fdeb29127b616e9c67261ebc/GUI.lua#L264

**Comment by kakysha** [comment]
Fixed
