### ISSUE TITLE
Slow data exchange

### ISSUE THREAD

**Issue by sasha-koss** [kakysha/HonorSpy#121]
I have no experience in coding lua so please bear with me if im wrong.
Broadcast:
1. Only broadcasting shortly after Player Death
2. Channels: Instance, Raid, Guild and Yell 

As you cant yell when youre dead, it wont work over that channel.
Most ppl are ranking over different CrossRealm AVs, so most death occur when they are with Players from different Realms - no real data exchange happens cause world pvp is dead.

Is it possible to exchange data over all channels on interface load while minding the timeout on broadcast - so we dont break the chat server again?

Edit:
Is it possible to exchange estimated Honor/HKs and list them in an extra Column?
For example if you get 15HKs on the day before reset you wont get added to the overall poolsize, right?

Best Regards
Sasha

**Comment by kakysha** [comment]
Right, the last day before reset is ignored, that's due to data being updated once a day, nothing can be done here. 

Honor / HKs is unnecessary information for ranking.

It always broadcasts through /g, that's how you get most recent of the data.

**Comment by sasha-koss** [comment]
"Honor / HKs is unnecessary information for ranking."
What? Thats totaly relevant for ranking, and adding one column to the db should be possible.
Would you implement it if i push the code?
