### ISSUE TITLE
Bug: Last Day Ignored & Wrong Poolsize / Feature Request: estimated Honor HKs

### ISSUE THREAD

**Issue by sasha-koss** [kakysha/HonorSpy#122]
Right, the last day before reset is ignored, that's due to data being updated once a day, nothing can be done here. 

Honor / HKs is unnecessary information for ranking.

It always broadcasts through /g, that's how you get most recent of the data.

_Originally posted by @kakysha in https://github.com/kakysha/HonorSpy/issues/121#issuecomment-576576535_

**Comment by sasha-koss** [comment]
Its possible because the data is already accessible and saved in the DB. And its mandatory for ranking to get a accurate realm poolsize to plan BR14 and BR13 slots.

Currently everyone with any amount of honor gets added to the poolsize but the correct cutoff is 15 HKs per week.

I can try to code and push it if you are willing to merge later.
Best Regards

**Comment by sasha-koss** [comment]
1. Add Columns as Button for Estmiated Honor and HKs like this @ Gui.lua row 230
btn = AceGUI:Create("InteractiveLabel") 
...

2. Set Button DataSource @ Gui.lua row 130

3. HonorSpy:BuildStandingsTable
I had to add 2 lines for estimated & HKs with these sources:
HonorSpy.db.char.estimated_honor 
HonorSpy.db.char.today_kills


4. The estimated Honor & HKs have to be saved in factionrealm.currentstandings.[HK]/[EH]
EstimatedHonor can be requested with sendAddonMSG via Whisper Channel on Mouseover data Collection?
Can only be requested from Honorspy Users and would require a few new functions.
Another Option could be that it gets broadcasted by honorspy users only and left blank in the meantime.
HKs can be read on mouseover and should be used to determine the poolsize.

5. How does this line work HonorSpy.lua row 120
`broadcast(self:Serialize(inspectedPlayerName, player))`
Does it only broadcast the player i inspected this moment? 
Is the Addon Broadcasting the whole Standing Table?


Help would be appreciated as i have never coded lua. Are there any debug tools or do you just hack something and restart WoW?

**Comment by tzn521** [comment]
看来各个运营商的军衔结算时间并不一致，所以导致无法满足所有服务器的要求。。希望大家能够列出军衔结算的具体截止日期。很多人把更新和截止搞混了。中国服务器是北京时间每周二早上7点截止。台服是另一个时间。

It seems that the various operators rank settlement time is not consistent. So you can't meet all the server requirements. I hope you can list the specific deadline for the settlement of rank. A lot of people confuse updates with deadlines. The Chinese server is 7 a.m. Beijing time every Tuesday. The dress is another time.

**Comment by kakysha** [comment]
I don't see what's its all about, but your points in your first message are wrong and won't be implemented

**Comment by sasha-koss** [comment]
Playing dumb when the Problems are obvious, nice. TY for your help
