### ISSUE TITLE
Please update to the new 10% DR for HKs

### ISSUE THREAD

**Issue by JEsuis-JE** [kakysha/HonorSpy#126]
As title says, they changed the diminishing returns on kills from 25% to 10%. People have commented on the curse page about a fix already, I just believe it should be updated for everyone or the calculations in the table wont be uniform.

> pdb39 
Posted 18 hours ago
#331
in Honorspy.lau, line # 143, I think if you change the line from:
est_honor = math.max(0, math.floor(est_honor * (1-0.25*((HonorSpy.db.char.today_kills[victim] or 1)-1)) + 0.5))
to 
est_honor = math.max(0, math.floor(est_honor * (1-0.1*((HonorSpy.db.char.today_kills[victim] or 1)-1)) + 0.5))     
That should change the new diminishing returns for HKs.

**Comment by Goldpaw** [comment]
I suggest also changing the suffix to the addon communication prefix from 4 to 5, to avoid new data being synced with people using the old version. Doesn't matter if you have the right data for yourself if you get much lower values for everybody else to compare with. 

I made a pull request with the changes:
https://github.com/kakysha/HonorSpy/pull/124

**Comment by yadgen** [comment]
> I suggest also changing the suffix to the addon communication prefix from 4 to 5, to avoid new data being synced with people using the old version. Doesn't matter if you have the right data for yourself if you get much lower values for everybody else to compare with.
> 
> I made a pull request with the changes:
> #124

4 to 5, where is it?

**Comment by Goldpaw** [comment]
What I do here: 
https://github.com/kakysha/HonorSpy/pull/124/commits/fc9699812252eb61a247bcd026b90ee2109e859f

**Comment by Goldpaw** [comment]
Line 6, I guess.
