### ISSUE TITLE
Readd sync channel to enable data sync between non-guilded players

### ISSUE THREAD

**Issue by Thaodan** [kakysha/HonorSpy#131]
Hey,
It would be great if sync with channels between players would be readded as it allows syncing data between players that are not in the same guild and are not always in the same grp.

On our server the community is split between guilds and it would be great to have an additional channel to sync honorspy data.

**Comment by Goldpaw** [comment]
This is no longer possible to do. 

Blizzard prevents syncing over any other channels than guild or groups now, they have made it impossible to sync between custom chat channels.
