### ISSUE TITLE
Massive Amounts of Player Duplicates This Week

### ISSUE THREAD

**Issue by stratoru** [kakysha/HonorSpy#142]
Starting just this week, honorspy has been creating massive amounts of duplicates of players. In the past, there was only a few here and there, but this week it seems that every single player on my list has 2 or 3 people who show as the exact same RP/Honor/Last Weeks Honor/etc. 

I have even found one person who is being shown as a "duplicate" (as in, they have way less honor/RP as shown in the honorspy table. Upon inspecting this persons honor tab manually, the Honorspy table updated with the correct version. 

This is really concerning still, however. With the number of duplicates on the table, it makes me wonder if the pool size is correct or not. Many of these "duplicated" players likely don't have 15 HK's for the week, and thus the pool size may be massively inflated in a false manner. Unless these players log back in/get inspected by someone else, they don't update correctly. This has massive implications for bracket stacking based on estimated pool sizes and has the rankers on my server in near panic-mode this week. 

I've attached an example image of the massive number of duplicates. 
![WoWScrnShot_053020_231308](https://user-images.githubusercontent.com/43893231/83344368-45b87a00-a2cb-11ea-83d3-b819becb089c.jpg)

**Comment by Realistspawn** [comment]
Yeah its a quite frustrating issue, I changed the commPrefix number on my addon, and spread it to the ranking community on my server thinking wouldn't get the troll scripts sending data, but its still happening so that's pretty frustrating so i'm back to the drawing to fix the issue

**Comment by Realistspawn** [comment]
I've noticed when looking at the honor spy saved variable that all after i changed the commprefix any fakes also had have issues in the lua.

Example
				["Enkei"] = {
					["**thisWSclass**"] = "PRIEST",
					["unitID"] = "mouseover",
					["class"] = "SHAMAN",
					["last_checked"] = 1591970555,
					["lastWeekHonor"] = 28843,
					["standing"] = 1096,
					["rankProgress"] = 0.933333396911621,
					["RP"] = 34667,
					["thisWeekHonor"] = 88725,
					["rank"] = 8,
ooo
				["Semyazza"] = {
					["unitID"] = "mouseover",
					["class"] = "WARLOCK",
					["**thisSlast_checked"**] = 1591943028,
					["last_checked"] = 1591950016,
					["lastWeekHonor"] = 16210,
					["standing"] = 1367,
					["rankProgress"] = 0.694117665290833,
					["RP"] = 45785,
					["thisWeekHonor"] = 3818,
					["rank"] = 8,
ooo
				["Deception"] = {
					[**"raned**"] = 1591966632,
					["class"] = "ROGUE",
					["RP"] = 28001,
					["rankProgress"] = 0.600000023841858,
					["last_checked"] = 1591953609,
					["lastWeekHonor"] = 4999,
					["standing"] = 1929,
					["unitID"] = "mouseover",
					["thisWeekHonohecked"] = 1591959354,
					["thisWeekHonor"] = 3873,
					["rank"] = 7,
ooo
				 ["Lvz"] = {
					["estHonor"] = 118288,
					["**throgress**"] = 0.431372582912445,
					["unitID"] = "mouseover",
					["class"] = "WARLOCK",
					["last_checked"] = 1591975446,
					["lastWeekHonor"] = 600791,
					["standing"] = 5,
					["rankProgress"] = 0.474509835243225,
					["RP"] = 47157,
					["thisWeekHonor"] = 231894,
					["rank"] = 11,

It appears every dup seems to have some sort of issue like this.

**Comment by Realistspawn** [comment]
Thinking about it, every duplication issue has a extra line of data, we should be able to make sure data is "fake" and flag it as invalid if has more then 9 of the variables we want to track.

**Comment by philomathikus** [comment]
@kakysha Any chance you could take a look at this issue? we have quite a few duplicates each weak and as an admin on our PvP ranking discord, I get quite a few whispers about potential breakers... The duplicates are easy to identify since they have the same standing as other players in the previous week :)

**Comment by kakysha** [comment]
It's a nasty bug that is very hard to track down cause it should happen on my side, but I don't PvP much anymore and don't encounter such problems. It can also be just a bad guys spamming fake data to everyone, which makes bug hunting a lot harder.
Also, I simply don't have any motivation atm, sadly. Probably at some time I will have some.

**Comment by Slivo-fr** [comment]
This is related to #198 (And I wish I would have read this one earlier)

I'm tracking it down and I may be able to fix it soon.

(This isn't fake or spoofed data, it's a honorspy bug)
