### ISSUE TITLE
GUI doesn't open

### ISSUE THREAD

**Issue by jkuehnis** [kakysha/HonorSpy#146]
Since the update to 1.7.5 I cannot open the user interface of Honorspy. After reinstalling and deleting the WTF HonorSpy files I can open the UI but only for once.

The /honorspy show command also does not respond.

**Comment by jkuehnis** [comment]
i'could fix it with deleting this folders/files:
..\WTF\Account\$accountName\$ServerName\$CharName\*
..\WTF\Account\$accountName\SavedVariables\honorspy*

**Comment by 0Net** [comment]
Same problem.

**Comment by MisterTooh** [comment]
Same; I've completely deleted Honorspy and AtlasLoot from my device; reinstalled honorspy yet the issue still persists.

This is the error I get in Bugsack:

`48x integer overflow attempting to store nan
[C]: in function `format'
honorspy\GUI.lua:63: in function `Show'
honorspy\GUI.lua:88: in function `Toggle'
honorspy\honorspy-1.7.5.lua:629: in function `OnClick'
...tlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua:144: in function <...tlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
(*temporary) = "%d (%d%%)"
(*temporary) = 2
(*temporary) = Infinite`

It's gonna be hell keeping track of bracket breakers and bots etc; this week.

**Comment by kakysha** [comment]
check now

**Comment by jkuehnis** [comment]
i've installed 1.7.6 seems like it's fixed. thank you for fast support!
