### ISSUE TITLE
Randomly added to strangers friends lists

### ISSUE THREAD

**Issue by Ditlevalfalck** [kakysha/HonorSpy#151]
Hi, i have a 60 hunter on Firemaw EU named Ra. Over the last 2 days, almost 100 people have written me asking if i'm a real player, and why i keep getting added to their friends list with a note saying "HonorSpy test". I've been told i will consistently, instantly, be readded to affected peoples friends list when they remove me from it. What the heck is going on, do you have some ghost code acting up? I do NOT have the addon installed myself.

**Comment by kakysha** [comment]
Its a bug with WoW game clients, for unknown reasons addon can add but not delete players with names consisting of 2 letters.

**Comment by Ditlevalfalck** [comment]
Okay, but the addon keeps adding me to their friends list after they manually remove me. Please fix this lol it's getting tiring.

**Comment by gurka** [comment]
Then add a check to make sure to never add players if their name is only 2 characters, to avoid this problem?

**Comment by Aleks1015** [comment]
This doesn't appear to be an issue anymore.  The client is successfully removing players with 2 characters in my recent testing as I was looking into this and considering a fix for it.

**Comment by Aleks1015** [comment]
This is likely due to the change to the Shadowlands client recently in Classic (Classic Era now) which was after TBC launched and applies to Season of Mastery.
