### ISSUE TITLE
Database not populating (not  reset day)

### ISSUE THREAD

**Issue by Thor-El** [kakysha/HonorSpy#153]
Hi there,

I've recently run into a novel issue wherein my databse doesn't populate, and this is on non-reset days too. It seems to fill with the info of players I run into, but doesn't handshake with them to pull info from their database into mine. I've tried a fresh install of WoW and the addon itself, and no luck so far.

I'm happy to provide any info you need to try and resolve this.

**Comment by emiltmadsen** [comment]
Having the same issue including not populating my database with new players I meet after the first 700 entries.

**Comment by walkerj90** [comment]
Same here. Doesn't even populate my own character at this point.
