### ISSUE TITLE
Annoying sound as someone is coming online all the time

### ISSUE THREAD

**Issue by Vpvladimirov** [kakysha/HonorSpy#165]
Previously there was an issue showing notification + sound for some people coming online all the time. Now I see the message notification in the chat is fixed but the sound remains.

**Comment by Aleks1015** [comment]
Thanks, yes I saw this reported and found it happening.  This has been resolved in a new pull request, I took the time to closely monitor and found another issue which delayed me submitting a request until I was certain this will fix the issues and another issues causing a flood a messages without breaking anything.

**Comment by Vpvladimirov** [comment]
@arog85 thank you very much for the fast response and fixing the issue. Waiting to update the addon.
