### ISSUE TITLE
Long cross realm player names overflowing

### ISSUE THREAD

**Issue by Slivo-fr** [kakysha/HonorSpy#179]
For ERA cross realm servers, the player name is sometime very long.

![image](https://user-images.githubusercontent.com/10325988/156256047-6a188195-8eb4-49a9-b48e-39f2611beb28.png)

Would it be possible to widen a bit the window or to truncate the names on the display to keep it on one line ?

**Comment by kakysha** [comment]
I do think this is fixable by widening the Name column a bit (just change the width in GUI.lua file)

**Comment by Slivo-fr** [comment]
I will give it a try tomorrow, thanks

**Comment by teelolws** [comment]
Yeah I noticed this as well just doesn't really bother me. Probably a better idea is to just only show the first letter of the realm name in that column.

**Comment by Slivo-fr** [comment]
Maybe 3 like blizzard does in chats ? For consistency :D

**Comment by teelolws** [comment]
Nah if I go with 3 characters, that one in your picture will still overflow. There aren't that many connected realms, it should be obvious from just one character.

Short character name but it was all I was able to get on short notice: 
![image](https://user-images.githubusercontent.com/49792789/156455945-0824b704-d5dd-4609-a80a-4cb0810c469b.png)

**Comment by Slivo-fr** [comment]
I'm fine with that too, just suggesting :D

**Comment by Slivo-fr** [comment]
We could also widen the column a little bit to allow the 3 letter suffix

**Comment by Slivo-fr** [comment]
@kakysha would this be fine for you ? 

I've widen the column a bit and used the 3 letter realm suffix blizzlike
![image](https://user-images.githubusercontent.com/10325988/157104279-97724352-8b9b-4b08-ad41-54df284f3b54.png)

**Comment by Slivo-fr** [comment]
I could just truncate past a given width but it would be less consistent, up to you !

**Comment by teelolws** [comment]
https://github.com/kakysha/HonorSpy/pull/186 truncated to 14 characters

**Comment by Slivo-fr** [comment]
Having the realm cut differently depending on the name lenght definitely looks odd to me

**Comment by teelolws** [comment]
Well if you can think of something better go ahead and code it and make a PR.

**Comment by Slivo-fr** [comment]
What about the screenshot above ? Looks more clean to me, what's you opinion ?

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/157126497-4e1cef90-ffbf-4900-82ad-0967d51f4cc3.png)

https://github.com/kakysha/HonorSpy/pull/186/commits/1d4729c4bfb2d0287505f88beb12d49eb157b79a

**Comment by Slivo-fr** [comment]
Sounds good, I would still truncate realm name to 3 chars for readability but this is another feature change.
Thanks :)

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/157127290-e54633ea-8f97-4094-a67d-b475e67f627b.png)

**Comment by teelolws** [comment]
What I'd like is a gap between the Name and KnownHonor column but IDK how to code that in.

**Comment by Slivo-fr** [comment]
I have no idea either, but the last screen looks good to me
