### ISSUE TITLE
Duplicated player entry in table

### ISSUE THREAD

**Issue by Slivo-fr** [kakysha/HonorSpy#184]
As you can see on this picture, 2 and 3 is the same player.  Same for 6 and 7.
Those data come from a level 1 char, alone on it's account, and never entered a BG. Most likely received it on com from another player.
Those duplicated players are from my own server if that somehow helps

![image](https://user-images.githubusercontent.com/10325988/156463505-4179bf20-8ee9-44d4-9ad9-f9773fbd2cd8.png)

**Comment by Slivo-fr** [comment]
Maybe we lack a realm check and strip somewhere ?

**Comment by teelolws** [comment]
Its the same issue from https://github.com/kakysha/HonorSpy/issues/175 which you even replied to.

There is something screwed up on Blizzards end which is making a player on another realm show up in-game as if they're from your realm. Because its so rare, I can't catch when it happens. Because I can't see it happen live, I can't find a workaround.

The good news: it only seems to happen once. From next week onwards you shouldn't see those players duplicated again.

**Comment by Slivo-fr** [comment]
I didn't think those would be linked, as it's only legits players from my cluster on this one.
Let me know if I can help somehow

**Comment by Slivo-fr** [comment]
I asked some help on the topic to someone knowledgeable (Meorawr) and here is some highlights. 

> It is possible - and expected - for C_PlayerInfo.UnitIsSameServer to transition from returning false to true when the same unit is queried over time. 
> However it will be fairly uncommon; basically for it to happen you need to query a player unit before the game has received their full information
> Which usually happens if you're idling and a nearby player logs in or you're at a hearthstone bind point that someone just hearthed to.
> Feasibly it could happen in the battleground/arena setup rooms since players are effectively "teleporting" in.

Then I asked if we double wrap that in another check to discard unreliable results 
> Usually GetPlayerInfoByGUID(guid) will return the globalstring constant UNKNOWNOBJECT for their name if given a player guid that isn't yet loaded. 
> (Same with UnitName(unit))

**Comment by Slivo-fr** [comment]
It does look like it duplicate player that I meet myself

**Comment by teelolws** [comment]
@kakysha assuming the fix I published worked, we're probably still going to get bad data from players who are slow to update HonorSpy. Do you think I should bump the Comm Prefix from 4 to 5, to discard data from players on old versions of the addon?

**Comment by kakysha** [comment]
Yep, let's do this

**Comment by teelolws** [comment]
Lets wait until Monday. I don't want to break addon comms when the week has already started (on US).

**Comment by Slivo-fr** [comment]
Isn't it better to break coms early than late in the week ?

**Comment by teelolws** [comment]
PR for comm prefix and some other changes up: https://github.com/kakysha/HonorSpy/pull/187

**Comment by Slivo-fr** [comment]
Not fixed, I'll try to debug that !

**Comment by Slivo-fr** [comment]
Looks solved in 1.8.7 will close after some more testing

**Comment by Slivo-fr** [comment]
This issue seems fully resolved :D
