### ISSUE TITLE
Report buttons and connected realms

### ISSUE THREAD

**Issue by Slivo-fr** [kakysha/HonorSpy#185]
When reporting a player from another server on the same ERA cluster using the GUI report button, HonorSpy try to report the same name from my original server and do not find it.

![image](https://user-images.githubusercontent.com/10325988/156811853-f756631a-a508-4679-a31a-32e50be802ae.png)

**Comment by teelolws** [comment]
Try this and lmk if it works. I don't have any data to test it with yet: https://github.com/kakysha/HonorSpy/pull/183/commits/8f269d685e72e60fc572cdccf2f38e1a19b81ce8

**Comment by Slivo-fr** [comment]
Bit better but still not working

![image](https://user-images.githubusercontent.com/10325988/156846301-aeb77bb1-0f7a-4936-8667-1eb436867b56.png)

**Comment by teelolws** [comment]
~~I'll make that check case-insensitive.~~

**Comment by Slivo-fr** [comment]
The minimap middle mouse click has also the same issue by the way !

**Comment by Slivo-fr** [comment]
And `/hs search Silverdragon-Finkle` is broken too 
> HonorSpy: Player Silverdragon-finkle not found in table

**Comment by teelolws** [comment]
Heres the problematic code, in HonorSpy.lua:

`	playerOfInterest = string.utf8upper(string.utf8sub(playerOfInterest, 1, 1))..string.utf8lower(string.utf8sub(playerOfInterest, 2))`

**Comment by teelolws** [comment]
Okay try this: https://github.com/kakysha/HonorSpy/pull/183/commits/4cc6ddf554e0c1db01fd96262a3373dbe48a928d

**Comment by Slivo-fr** [comment]
Works for search and report button, minimap middle click still lacks the realm

**Comment by teelolws** [comment]
Should fix the minimap middle click: https://github.com/kakysha/HonorSpy/pull/183/commits/68fa44bc001043f38979092224333b6b060cb7b0
