### ISSUE TITLE
GUI doesn't display every character 

### ISSUE THREAD

**Issue by Slivo-fr** [kakysha/HonorSpy#188]
As you can see, 36 players are known by Honorspy but I can only scroll to the 32th
This is related to the number of "bracket" row displayed on the screen I believe

![image](https://user-images.githubusercontent.com/10325988/157523801-79da2a98-d721-4674-a76b-953535b394a7.png)

**Comment by Slivo-fr** [comment]
I may be able to provide a fix, testing in progress

**Comment by Slivo-fr** [comment]
As we reverted it, this issue should be reopened to discuss the potential implementation.
Can you please do that ? :)

**Comment by Slivo-fr** [comment]
I can push another implementation that should not cause any issue, but will leave few empty spaces at the bottom of the table.
What do you think about it ? (The number of empty space is equal to the number of bracket separator that _could_ be displayed, they are the same height as other buttons)

![image](https://user-images.githubusercontent.com/10325988/160283442-60c1fe66-2b47-492a-937e-b6acf649e154.png)

It's better than having the last rows hidden in my opinion

**Comment by teelolws** [comment]
Yeah I don't think anyone is going to care about empty rows at the bottom. Fine with me.
