### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by tftracy** [kakysha/HonorSpy#199]
Hi, hope you are well. My honor spy is comepletely blank. I use cureforge usually but have even tried to re - install from downloading directly from get.  Ive tried to dump my cache wtf and all addons folder.  Pretty sure I have curse forge not saving settings. This problems has persisted for 2 weeks now and I though well maybe next week after reset and honor rolls over on Wednesday.  Nothing has worked still got nothing in my database. Any other suggestions would be greatly appreciated.

**Comment by Godmatik** [comment]
Confirmed - latest version isn't populating any data

**Comment by kakysha** [comment]
What are the servers you playing on?

**Comment by tftracy** [comment]
I play on the season of mastery server Jom Gabbar.  I know other peoples are working, but I don't know what version of HonorSpy they are using.  I always update my add-ons.

**Comment by Godmatik** [comment]
Also play on Jom Gabbar, a few of my guildies reported similar issues with the newest version of no data being populated.

You can download an older version from a couple of weeks ago and it works and picks up data, however it also has saved data from ~2 weeks ago that don't clear from the table, so the results are not accurate regardless

**Comment by kakysha** [comment]
@Slivo-fr @teelolws can you guys look into this?

**Comment by teelolws** [comment]
Looks like Silvo forgot to account for realms that have spaces in their names. I've fixed this with: https://github.com/kakysha/HonorSpy/pull/200

@kakysha can we get an urgent pull and release on this

**Comment by tftracy** [comment]
You guys are the best thank you for all your work on the addon I'm using the older build for now will grab new build when available.

**Comment by teelolws** [comment]
The fix is up on Curseforge now. Better to use that as communication between old/new versions won't work.

**Comment by Slivo-fr** [comment]
Hmm yeah this is the validation regex we've been working on together Teelo !
Tbh I had no clue there was servers with space in their names
I've suscribed to issues, I'll be notified next time

**Comment by Godmatik** [comment]
Just downloaded and tested 1.8.8 on Jom Gabber, issue resolved, data is being populated, can be closed.

Thanks!

**Comment by tftracy** [comment]
There are a few things still broken. Wish I understood the code to be able to help, but I only know a little of python and arduino stuff. So, maybe I can list them here.
1. Adding random friends with the note honorspy testing
2. wont show players kills on the HonorSpy Standings window nor estimated rank and % that kind of info is gone. Report button will still show it.
3. /hs search requires you to input more than just character name. (maybe not a bug but the format and length of proper character name is annoying)

I know others on my server had mentioned other things but I'm drawing a blank on them now.  Let me know if better to just stop feedback.

Best,
T

**Comment by Slivo-fr** [comment]
Feedback is always valuable, however it would be easier to handle each problem if you open a new dedicated issue for each imo

**Comment by teelolws** [comment]
My fix in #200 introduced a new bug: the UI thinks its a different realm now and shows the realm name:

![image](https://user-images.githubusercontent.com/49792789/161722497-52fb9aaa-d018-415c-bdcd-57239c531afd.png)

PR for fix in https://github.com/kakysha/HonorSpy/pull/204
