### ISSUE TITLE
Potential Issue with Honor tab

### ISSUE THREAD

**Issue by bgfds** [kakysha/HonorSpy#26]
On the beta the honor tab wouldn't update your honor until (10am?) the next day.

any plans to get around this? could you update your addon to track your honor from the combatlog or w/e and update every1 with your true # throughout the day?

**Comment by kakysha** [comment]
https://us.forums.blizzard.com/en/wow/t/q-a-compilation-wow-classic-development-team-ama/260760
 
Q: How does that work with the honour calculations? They were always done in downtime. 101
A: When restoring the honor calculation code we re-wrote it so it can work while the game is live. Realms do not need downtime for honor to update.

You talking about that?

**Comment by bgfds** [comment]
i think that's referring to the weekly honor calc right? like when they do decay

on the beta the inspect and character honor tab didn't update until the "day" was over, making stacking difficult

 i guess we'll find out in a few hours

**Comment by bgfds** [comment]
yep, the "Honor this Week" doesn't update in real time so you can't know how much honor you currently have, it only updates once per day.

**Comment by bwjohnson0** [comment]
I'm currently PvPing, and not seeing any populations on the table. Does the daily calculation need to update before the table begins to populate? I'm able to insect others' honor, nothing shows up in the Addon.

**Comment by bwjohnson0** [comment]
So with this, we can except the table NOT to populate until Friday (11/15/19)? The table is currently not populating with anyones # of HKs.

**Comment by kakysha** [comment]
Thats really sad, guess HonorSpy can only update the table once per day.
There is no point in "predicting" your current honor, as the other players in table will not have their honor updated during the day and you will have fake feeling of advantage.

But I will probably add it, just for information

**Comment by bgfds** [comment]
atleast if it's added it will allow us to track our own honor and our premades honor so we can stack

**Comment by bgfds** [comment]
u also need to account for decay urself, the ingame reported honor in the chat isnt counting for decay lol

**Comment by kakysha** [comment]
implemented it in v1.3.0
