### ISSUE TITLE
Current week honor estimation

### ISSUE THREAD

**Issue by cannonpalms** [kakysha/HonorSpy#30]
I will soon be developing a small library for keeping track of diminishing returns and applying them to the honor values shown in the chat window in order to maintain an estimation of honor for the current week. Is this something you would be interested in including in HonorSpy? It would be another data point to distribute to other addon users upon death/etc. You don't have to add this estimation to the players actual reported honor unless the estimation proves to be accurate.

**Comment by kakysha** [comment]
would be great!

**Comment by kakysha** [comment]
Implemented it in v1.3.0
