### ISSUE TITLE
Frame disordered

### ISSUE THREAD

**Issue by Qcat0214** [kakysha/HonorSpy#32]
after the data is full, the main window frame is disordered

<img src='http://i2.tiimg.com/609861/da6cdfe29a9b8acd.png'>

**Comment by Adyne** [comment]
It's a bit better for me, but in fact the text is messed up.
"Brackets" are inside the line not below (Like 3 pixels too high) and all the text on the bottom is inside the window, "Pool Size" is unreadable for example.
Hope a method is coming to delete users offline, 1-2-3-4-5-9-10 is not updated messing up the whole list.
![Capture](https://user-images.githubusercontent.com/35479752/69361173-34dbdb80-0c8c-11ea-81b9-2ce89f84757d.PNG)
