### ISSUE TITLE
Feature suggestion: synchronize button

### ISSUE THREAD

**Issue by Olorun** [kakysha/HonorSpy#36]
Would be nice to have some way to manually force a synchronizing of data. Some request that can only be started by a raid/group leader (or assist). This way, you could set up a group to spread data around.

**Comment by Olorun** [comment]
Possibly with an window popping up so that users can confirm/deny the request to update.

**Comment by kakysha** [comment]
Just join a group / raid and die, you will trigger syncing of your data to the rest of raid members.

**Comment by Olorun** [comment]
I know about the death-trigger, it just seems like it could be nice to have the synch button for when you're in your capital city and share the data with other people . Having to suicide while I'm in Orgrimmar just to share the data seems a bit excessive, that is why I suggested it.

**Comment by kakysha** [comment]
You also share the data after every successful "inspect" of the player, that is on mouseover or target of any other guy you instantly distribute this new information to others.

**Comment by knasen88** [comment]
I'd also prefer a manual option, if you pvp with the same people you won't really get to update it with outsiders.

**Comment by kakysha** [comment]
if you pvp with the same people, you obviously die at least once and share the whole database with all of them, and then while inspectin more players you also share this information.
