### ISSUE TITLE
Weekly reset is too early

### ISSUE THREAD

**Issue by Olorun** [kakysha/HonorSpy#37]
My honorspy already reset, but the reset is going to happen in 70 minutes from now.

**Comment by kakysha** [comment]
Ok, I need the exact time for weekly reset then. Right now it is set at 10AM UTC Wed, does it differ for your server?

**Comment by Olorun** [comment]
Pretty sure it's 10 AM EST Tuesday, because that's when our server restarted. (8 AM PST)

**Comment by kakysha** [comment]
So, probably that: Tuesday, 15:00 UTC for the US, Latin and Oceanic servers and Wednesday 07:00 UTC for the European servers.

Confirm?

**Comment by greath2217** [comment]
its kinda randoom. some ppl got it at 7 utc and some got it way later. mine got reset at 11 utc

**Comment by Olorun** [comment]
Yeah I think it only resets for people that are logged out to be honest. If you are logged in and keep playing, the "today" honor doesn't seem to be updated to the "yesterday" part..at least in my experience. Has anyone experienced resets while they were logged into their character?

**Comment by kakysha** [comment]
3 PM UTC Tue (7 AM PST Tue) - US and Oceanic
7 AM UTC Wed (7 AM UTC Wed) - Europe
10 PM UTC Wed (7 AM KST Thu) - Korea

Probably this?

**Comment by kakysha** [comment]
Should be fixed in v1.4.3
