### ISSUE TITLE
24 hour kill dr reset at kill calc or after 24hrs?

### ISSUE THREAD

**Issue by bgfds** [kakysha/HonorSpy#39]
Not all Honorable Kills are valued the same, however. Killing the same enemy multiple times will result in a decreasing amount of Honor gained until they aren’t worth anything more through the end of the day, when the system resets the diminishing returns. 

https://worldofwarcraft.com/en-us/news/23221132/wow-classic-world-bosses-and-pvp-honor-system-available

**Comment by kakysha** [comment]
It is called Diminishing Returns and its already there, update in any case.
They reset when daily honor reset happens.
