### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by 0vertime** [kakysha/HonorSpy#4]
When the list gets too big, it seems to cause some sync lag in battleground and is slow to open. Currently have 2000+ players on it on Anathema. Maybe add some option to limit what is saved? Eg. top-100 per week/last week.

**Comment by phendrome** [comment]
Yup it goes crazy even if I've set the limit to 500MB for my addons.

**Comment by kakysha** [comment]
You must not experience any lags on sync, its throttled by default. Can you explain what lag spikes you get in battlegrounds?
And how many ppl with ThisWeekHonor > 0 do you have in your table on Anathema?

**Comment by 0vertime** [comment]
I already nuked mine. Basically it was doing stuttering every now and then in BGs when enabled.

**Comment by kakysha** [comment]
Added tumbler to show/hide players with ThisWeekHonor == 0, it must significantly decrease number of rows and increase table open perfomance.
Will continue research against those lag spikes in BG later.

**Comment by kakysha** [comment]
v2 released, try it now and check if lags are gone
