### ISSUE TITLE
Estimated Honor is removed from the /hs show window.

### ISSUE THREAD

**Issue by bgfds** [kakysha/HonorSpy#40]
Also, the kills were not reset during the daily update today so the estimated honor will be completely off :)

**Comment by kakysha** [comment]
What do you mean by "removed"? And the daily reset is fixed today already.

**Comment by bgfds** [comment]
https://i.imgur.com/ka2GQpP.png
is it because i randomly havent been inspected?
prior to todays updates it showed estimated honor at the top? now it doesnt

**Comment by kakysha** [comment]
Probably you had your PvP week reset? Cause it clearly states that you don't have 15 kills yet. Thats why it is not showing your honor / standing yet.

The question is - if it actually was a PvP week reset, why you have data in your table still. US / Oceanic? I still had to fix the reset times for ya then.

**Comment by bgfds** [comment]
Yes, it was us. Reset time is 10AM EST on my server, Faerlina
I also have way more than 15 kills at this point and the addon isn't updating. 
https://i.imgur.com/jdLtJde.png

**Comment by kakysha** [comment]
It will only update tomorrow, when "This Week Honor Kills" will be >=15 and you get some honor for this week.
I will try to fix PvP week reset asap.
