### ISSUE TITLE
Additional CSV information

### ISSUE THREAD

**Issue by madxmike** [kakysha/HonorSpy#41]
I am currently working on a website to allow users to upload their HonorSpy data, and have the server aggregate data for all the classic wow servers into a viewable and searchable list (https://github.com/Madxmike/honorranks). I plan on it working much like the old honor ranking page on warcraft.com worked. However, I've ran into an issue trying to use HonorSpy's data set.

One of the problems I am facing is how to verify that the csv's being uploaded are actually for that server / faction. With the data set right now, I would have to rely on users accurately selecting their server/faction when they upload their data, or manually verifying it in some way. As such, would it be possible to have a column for the server and faction of the players to be added?

**Comment by kakysha** [comment]
I think you can decide on faction by searching for paladins/shamans. For the server, probably I will include it in csv output, as I need it anyway for predicting correct weekly reset times.

**Comment by madxmike** [comment]
Good idea on the faction part, and thanks look forward to the update :)

**Comment by ffalor** [comment]
@Madxmike I was actually in the process of doing this, but you seem farther along than me. Interested in seeing the outcome.

One thing I did notice is the export to csv functionality only exports around 1800 rows for me despite the pool being over 8k. This might be a limit of the window it is exporting to. @kakysha is there a way to export it to the file system?

**Comment by kakysha** [comment]
@ffalor it is already on your disk, check you SavedVariables folder.
CSV export was meant to be used by players to paste it into google spreadsheet.

**Comment by Dykarbremsen** [comment]
You can downvote my comment or remove it if this is a stupid request 😄 
But can you give a lua file that just prints all the data from the lua table as text. soring the rest is easy for me but getting the hang of how Lua works is just confusing me

Sorry for stupid request

Reason for doing this is i want later to sort out all guild members and have a internal rank system for our guild.
