### ISSUE TITLE
Chat Channels

### ISSUE THREAD

**Issue by dagochen** [kakysha/HonorSpy#42]
The addon changed the order of my chat channels and switched everything around. That should not happen I guess...maybe you can fix that?
1. General
2. Trade
3. Local Defense
4. Worldchat
5. my private hunter channel
and now its

1. nothing
2. nothing
3. nothing
4. HonorSpy
5. Worldchat
6. my private hunter channel
....

**Comment by kakysha** [comment]
yeah, chat channels are a bit of a mess to deal with, I did my best (introduced delays for joining and leaving the channel). 
Also, you can't have more than 10 channels or be in the same channel twice. 
Also HonorSpySync channel should have number +2 from your last own channel

**Comment by Olorun** [comment]
I experienced the same after the update. My channels used to be similar to what dagochen described, I have several empty/skipped numbers.

**Comment by kakysha** [comment]
I skip two numbers on purpose to let you join new channels and keep numbers in order

**Comment by Finrodi** [comment]
I guess guild sync is fine in the meanwhile due to them (most likely) syncing through the channel and as long as they do it I should get the data as well (through guild)?
