### ISSUE TITLE
Channels messing up

### ISSUE THREAD

**Issue by Finrodi** [kakysha/HonorSpy#46]
Ever since the sync through channel I think it messes up all other channels and puts general/trade on 4th/5th slot. https://i.imgur.com/AjfUzcx.png

**Comment by kakysha** [comment]
Same as #42. Some info regarding channel problems in there.
I don't know why it happening for some users. But as a solution for it you can disably syncing over separate chat channel and use /guild instead. The settings for that is in addon Settings.

**Comment by dbtdsilva** [comment]
I just created another window, joined the channel manually and never had problems again.

**Comment by dagochen** [comment]
![image](https://user-images.githubusercontent.com/5236186/69452689-8a82b780-0d62-11ea-939a-2d6c36c6e1ba.png)

**Comment by dagochen** [comment]
you put honorspysync at index 0+2 and not maxchannelindex +2

**Comment by kakysha** [comment]
I put them at maxchannelindex +2.
You can't pick a specific number for channel, you can only join and leave them, server gives you last index + 1 when you join a channel. I join 3 channels, then leave first two.
Probably I should increase the timeout before joining channel, as it seems like 5 seconds is not enough for some clients to join "default" channels.

Will increase the timeout in next update, lets hope it helps.
