### ISSUE TITLE
Ranking points

### ISSUE THREAD

**Issue by Olorun** [kakysha/HonorSpy#48]
Not sure how RP are currently determined in HonorSpy, but there is a function that can be used for obtaining rank points. Below is a macro that I use for it, I'm sure you can rework the function to improve the RP part of HonorSpy.
/script P=(math.floor(GetPVPRankProgress(target)*10000))/100 W=UnitPVPRank("player") N=(W-6)*5000+5000*P/100 Q=(W-5)*5000-N*0.8 SendChatMessage("Rank progress: "..P.."% ".."Current RP: "..N.." RP to next rank: "..Q.."","emote")

**Comment by Olorun** [comment]
Do note that this only works for self-reporting, but at least the players using HonorSpy could share better data that way.

**Comment by kakysha** [comment]
Why do you say "better" data? Are you not satisfied with current RP in the table?
If you see some strange "round" numbers like 2000, 3000, 5000, all that players have Rank1, which is technically a 0 RP.

Have a look at the code: https://github.com/kakysha/HonorSpy/blob/classic/honorspy.lua#L112

**Comment by Olorun** [comment]
You're right, guess I just had a bunch of bad data!
