### ISSUE TITLE
Old Data

### ISSUE THREAD

**Issue by Elyssen-1** [kakysha/HonorSpy#49]
The correct Rank 1) data starts at 22, even 24 is a day old.
This is messing up the whole table.
They never update and it only gets worse, went from 3 "bugged" person to 22 in hours.

![Capture2](https://user-images.githubusercontent.com/35479752/69417730-8e3e1c00-0d19-11ea-8d0e-c3455c4b4533.PNG)

**Comment by kakysha** [comment]
This is due to Blizzard's bug on this week. It should be good next week reset.
