### ISSUE TITLE
Bracket sizes wrong values

### ISSUE THREAD

**Issue by AmNegative** [kakysha/HonorSpy#52]
It looks like bracket sizes are based on pre-1.12 versions which leads to smaller top end brackets than reality.

EG: Bracket 14 should be .003 rather than .002 

Values for the size of each bracket post 1.12 can be found on this page.
https://wowwiki.fandom.com/wiki/Honor_system_(pre-2.0_formulas)

**Comment by kakysha** [comment]
Do we have proofs that the server is on 1.12 values?
Cause honor DR = 25%, which was true for pre 1.7 patch

**Comment by Nelythia** [comment]
On Shazzrah Horde my Honorspy had 6700 entries last week and from calculating my standing 18 (12001 RP, lowest in Bracket 1) it seems the Pool has been on roughly 9000 horde players with atleast 15 hk's. Lowest standing we have seen in the guild was 5800.

**Comment by greath2217** [comment]
poolsize was 4229 on the server skeram. we know this because we gave a lvl 1 the 15 hks and he got 1 honor per kill. standing 13 was the beginning of braket 2. we know this because standing 13 got 12000 rp. 4229 x 0.003 = 12.687 = 12

**Comment by Deviljho-flamelash** [comment]
On flamelash-EU, last week 13 ppl were in the first bracket, estimated pool size was in the 3900+. To have 13 in bracket one you need pool size between 4167-4499. If it was using pre 1.8 formula we would see a lot less people in the 12k RP+. Here a screenshot to prove it. https://i.imgur.com/brvDu1G.png
*rounded up of course)
(4167/0.003 = 12.5 ---- 13.49 = 4499 x 0.003)

**Comment by cannonpalms** [comment]
On Skeram Horde:

* Bracket 1: 13 slots
* Bracket 2: 34 slots
=> `34 / 13 = 2.615...`
* Correct 1.12+ breakpoints: `0.008 / 0.003 = 2.6666...`
* Incorrect pre-1.12 breakpoints: `0.007 / 0.002 = 3.5`

This is conclusive. Even accounting for rounding errors in weekly standings we do not come near the pre-1.12 ratio of 3.5. 

Cannon

(P.S. Sorry for not getting back to you on estimated honor. Something came up last week that has been occupying my attention. I see you’ve solved the problem yourself, and the implementation looks quite good!)

**Comment by cannonpalms** [comment]
On Skeram Horde:

* Bracket 1: # 12
* Bracket 2: # 32
=> `32 / 12 = 2.6666...`
* Correct 1.12+ breakpoints:
=> `0.008 / 0.003 = 2.6666...`
* Incorrect pre-1.12 breakpoints:
=> `0.007 / 0.002 = 3.5`

This is conclusive. Even accounting for rounding errors in weekly standings we do not come near the pre-1.12 ratio of 3.5. 

You are correct that Blizzard did decide to use pre-1.12 diminishing returns for Classic, but this was just a sneaky #SomeChanges to reduce camping. For added weirdness, Classic also uses 1.8+ honor per kill values. Blizzard did not reuse the backend for honor calculations according to their AMA. Rather, it was rewritten, at least partially, to not require a realm downtime for honor to update. Who knows, perhaps one of these observed parameters is a bug, but for now, all I can tell you is how honor currently works. 

Cannon

(P.S. Sorry for not getting back to you on estimated honor. Something came up last week that has been occupying my attention. I see you’ve solved the problem yourself, and the implementation looks quite good!)

**Comment by kakysha** [comment]
Ok, thank you guys! Changed in v1.4.10.

**Comment by Finrodi** [comment]
I can't believe that this is true actually, we had exactly 19 BR1 spots last week with #19 getting 12001 RP, Poolsize was around 8800. Now the poolsize is 6700 for me and it already shows 20 BR1 spots.

**Comment by kakysha** [comment]
6700*0.003 = 20.1 ≈20, this is 1.12 values (it is now)
8800*0.002=17.6 ≈18, this is pre-1.12 values (it was before)

So, who is right?)

**Comment by Nelythia** [comment]
> I can't believe that this is true actually, we had exactly 19 BR1 spots last week with #19 getting 12001 RP, Poolsize was around 8800. Now the poolsize is 6700 for me and it already shows 20 BR1 spots.

Ehm, yeah. Because HonorSpy got updated and especially fixed an important bug that displayed duplicates. Which still happens by the way if people keep using that bugged version.

So while your HonorSpy could have displayed the 8800 Pool, it could potentially have been way less. Considering how I literally had 10 duplicates on bracket 1 yesterday, I don't think that is far fetched to think. Especially when a week ago everyone was using a bugged version.

Right now on Shazzrah Horde the HonorSpy pool is 4917 with 15 Bracket 1 spots. Seems perfectly accurate to me when I substract around 50-100 for currently bugged duplicates.
It is definitely on 1.12 brackets. No doubt on that from me.

**Comment by Finrodi** [comment]
I deleted my list quite a few times to make sure its quite accurate and Gehennas is known to be one of the biggest servers (especially horde side). Of course I might be wrong but Id imagine if it says 8800, there still might be a few people left who didnt get logged (some low levels or so). But right now with current formula it already shows 2 bracket 1 spot more than it was last week and I'd imagine if anything fewer people are pvping.

**Comment by AmNegative** [comment]
I wouldn't look at your Honor Spy's pool size due to the duplication bugs that have happened with the previous versions.

Last week Skeram Alliance:
Standing 7 was bottom of BR1

You need 15 HKs to be counted into the ranking pool and I had a character  with 707 honor for last week which landed on standing 1947.
For 7 BR1 spots on Skeram Alliance we would have needed 3500 characters with more than 15HKs for that to be possible. I'm more than willing to believe that there is no way that over 1500 characters were under 707 honor and with more than 15HKs.

**Comment by cannonpalms** [comment]
@Finrodi What was the standing at the bottom of BR2? It is far less reasonable to assume that the pool size is accurate than it is to assume that the standings for BR1 and BR2 are accurate. Thus, calculating breakpoints with the method I showed previously is optimal.

**Comment by Finrodi** [comment]
@cannonpalms https://i.imgur.com/jgF2pKq.png Guess 50 was the cutoff.

**Comment by cannonpalms** [comment]
@kakysha Per the numbers from @Finrodi --

* Bracket 1: # 19
* Bracket 2: # 50
=> `50 / 19 ≈ 2.632`
* Correct 1.12+ breakpoints:
=> `0.008 / 0.003 = 2.6666...`
* Incorrect pre-1.12 breakpoints:
=> `0.007 / 0.002 = 3.5`

1.12+ breakpoints are still respected. The moral of the story is not to place trust in the size of the ranked pool. Perhaps as time goes on and the userbase grows, it will be more accurate, but for now, relying on accurate data for the top brackets is a better approach.
