### ISSUE TITLE
Suggestion: Show Rank Progress in % next to Rank in Honor Tab

### ISSUE THREAD

**Issue by Nelythia** [kakysha/HonorSpy#54]
Hi Kakysha, thanks for your work on Honorspy. It is much appreciated.

I have a suggestion based on this addon I used on Privateservers: https://www.curseforge.com/wow/addons/project-1215

It would display your current rank progress in % next to your rank in the Honor tab. I always found it quite useful and think it'd be a good addition to Honorspy as I haven't found any addon doing it yet.

**Comment by kakysha** [comment]
Hi Nely! I will leave this open to implement it sometimes in the future. Can't give you an ETA on that yet :)

**Comment by kakysha** [comment]
Done
