### ISSUE TITLE
Duplicates popping up

### ISSUE THREAD

**Issue by sbrkopac** [kakysha/HonorSpy#55]
Not sure why we are getting duplicates all of a sudden on some values. 

![image](https://user-images.githubusercontent.com/1939712/69485708-64abf000-0e00-11ea-8d88-8a39fa97a5a2.png)

It might be something with an old version causing syncing issues? Is there a way to change the syncing to only only sync if the incoming data is from another player with the latest version of the add-on?

**Comment by kakysha** [comment]
yes, thats because of old versions and users updating their addon. They have their database corrupted and after update they sync their corrupted database to new versions.

**Comment by sbrkopac** [comment]
Is there a way to prevent old versions of the addon from syncing? Or at least prior to the version that was very broken.
