### ISSUE TITLE
Estimated Honor gained wrong values

### ISSUE THREAD

**Issue by dagochen** [kakysha/HonorSpy#56]
Values differ from what I really get. Honorspy says I gain 15000 Honor a day and in the honor tab it says only 14500 honor the next day.

**Comment by kakysha** [comment]
Yes, same happens for me too. I don't know where it comes from, you can clearly see number of kill counts and honor gained after every kill, either the server does not count some kills or DR are a bit bigger.

**Comment by Nelythia** [comment]
https://us.forums.blizzard.com/en/wow/t/honor-not-being-calculated-3-8-am/371752

I personally don't have this issue, or atleast I don't notice any honor missing. But maybe it is bugged for some players during that time period.

**Comment by kakysha** [comment]
One more Blizzard bug which fucks HonorSpy?

**Comment by dagochen** [comment]
The addon HonorAssist calculates the correct values, so it must be the addon.
