### ISSUE TITLE
Slow to open

### ISSUE THREAD

**Issue by 0vertime** [kakysha/HonorSpy#6]
Currently on monday my week looks like this: http://pastebin.com/VxXx1d6H (Total around 4K with >15hk)
It takes about 40 seconds to open it and another to export it - it also freezes game for the duration completely. Personally I only care about top 50-100, so seems unnecessary data is collected.

**Comment by kakysha** [comment]
Working on a solution to limit the number of rows shown, but allowing you to see pool size.

**Comment by kakysha** [comment]
@0vertime @furnicarium v3 released! 
Lags have been beaten up!
You can LIMIT number of players shown in table, default is: 750. Standings table opens almost immediately.
You can search for any player standings now! Type "/hs search player_name" to check.
Improved perfomance of CSV export. No more disconnects!
