### ISSUE TITLE
Estimated Honor Calculation is off by ~ 20%

### ISSUE THREAD

**Issue by sasha-koss** [kakysha/HonorSpy#60]
The estimated Honor for the next day is off by about 20%, watched it the last 3 days.
126.644-111.548= 15.096 from HonorSpy

The Value from Honor DR Tracker is much closer to what you get the next day.
Estimated Honor is 12.091 @ Honor Tab under Today where the dishonorable kills for the day used to be.

Edit: already fixed

**Comment by Nelythia** [comment]
He already fixed it, the update just wasn't pushed available yet.

https://github.com/kakysha/HonorSpy/commit/f7810d836787fe183ee86186266bac50bb15bccd

**Comment by kakysha** [comment]
Update is live now.
