### ISSUE TITLE
First kill of the day issue

### ISSUE THREAD

**Issue by exus85** [kakysha/HonorSpy#61]
When I logged in today (after the daily reset) my honor tab was showing this:
![HS_issue1](https://user-images.githubusercontent.com/27153298/69626333-b5ae2500-1048-11ea-9aa0-5070ad082204.jpg)
0 kills but (Honor: 9521), that should be 0 right?
and also under This week "Honor  37129 (39356)" it should be 37129 (37129) 
After my first kill it's showing
![HS_issue2](https://user-images.githubusercontent.com/27153298/69626422-edb56800-1048-11ea-9696-3a6afadb2da5.jpg)
It should be (Honor: 199)
and lastly my second kill:
![HS_issue3](https://user-images.githubusercontent.com/27153298/69626508-150c3500-1049-11ea-8f3f-22ceab7386c9.jpg)
(Honor: 40, my first kill was ignored)

**Comment by kakysha** [comment]
should be fixed now, update
