### ISSUE TITLE
Sync doesn't seem to work reliably

### ISSUE THREAD

**Issue by knasen88** [kakysha/HonorSpy#63]
my friend https://imgur.com/a/cbctUxy
mine: https://i.imgur.com/NAhLnjD.png (currently on alt with buffs)
we've been in same party, died together etc etc. Tried turning on guild sync still doesn't update.
Other guild / party members also can't get his table 
(missing about 2500 from the pool?)

**Comment by Nelythia** [comment]
It does not update instantly like on privateservers. On a pool difference of that size it will compare each of your both entries one by one and add the missing players in your poolsize step by step.

**Comment by showyk** [comment]
I never played on private servers.
but it is realy normal? bcuz, everyone im asking did not have this problem, they still can see all their data.

**Comment by kakysha** [comment]
This was due to the bug with week reset. Sync is woring reliable, old data is just discarded for one guy and saved for another.
