### ISSUE TITLE
CSV Records Include Trailing Comma

### ISSUE THREAD

**Issue by madxmike** [kakysha/HonorSpy#66]
Hello,

Currently the CSV produced by the export gives the following result:

```
Leftshark,ROGUE,193638,166684,1,13001,4,11/26/19 01:14:12,
Poiytley,ROGUE,142439,70379,31,11079,4,11/25/19 22:40:59,
```

According to [RFC 4180](https://tools.ietf.org/html/rfc4180#section-2) each record is supposed to be terminated with a new line character instead of a comma. Here is the result according to the RFC:

```
Leftshark,ROGUE,193638,166684,1,13001,4,11/26/19 01:14:12
Poiytley,ROGUE,142439,70379,31,11079,4,11/25/19 22:40:59
```

Currently running into this issue parsing the CSV into a struct using [Go's encoding/csv](https://golang.org/pkg/encoding/csv/). I'm unable to parse the input as intended. Able to work around it by considering the last comma as another field, but just wanted to bring it up for you attention

Thanks!

**Comment by kakysha** [comment]
For parsing needs just use SavedVariables file on disk. 
CSV is for Google spreadsheet. 
But thanks for the report.

**Comment by madxmike** [comment]
Alright thanks!
