### ISSUE TITLE
Some player keeps adding fake data to the localDB

### ISSUE THREAD

**Issue by r0hitch0pra** [kakysha/HonorSpy#67]
The entire Incendius-Horde server has been ruined because someone added fake players with fake honor data. I've modified my local copy to correct this and ignore future syncs, is there a feature request that can help with this?

**Comment by sasha-koss** [comment]
#58 
"Note for future readers: I considered many approaches how can we eliminate this "bad" data, and all of them brought me to dead ends or super complex solutions. There are no feasible ways of checking for the existence of specific player names, neither we can reach any consensus on "correct" distributed database state."

**Comment by kakysha** [comment]
yes, basically just wait for week to reset and hope this bad guys get tired of doing bad things

**Comment by thestinger** [comment]
They're submitting corrupt data, so the addon can't display anything. They set last week's honor to a string that's not a valid number. It would be nice to handle corrupt data so the worst they can do it submitting junk data rather than breaking it from working at all. It currently hits an uncaught exception when opening the main UI.

**Comment by kakysha** [comment]
thats obviously a bug, can you open the proper bug report or at least give me the error?

**Comment by thestinger** [comment]
```
Message: Interface\AddOns\honorspy\honorspy-1.5.4.lua:244: attempt to compare number with string
Time: Thu Nov 28 15:42:31 2019
Count: 1
Stack: Interface\AddOns\honorspy\honorspy-1.5.4.lua:244: attempt to compare number with string
Interface\AddOns\honorspy\GUI.lua:35: in function `Show'
Interface\AddOns\honorspy\GUI.lua:78: in function `Toggle'
Interface\AddOns\honorspy\honorspy.lua:486: in function `OnClick'
```

They set last week's honor to a string like 'honor spy disabled'. They're also setting the class to death knight which might cause problems.

**Comment by kakysha** [comment]
fixed

**Comment by thestinger** [comment]
Thanks!

**Comment by thestinger** [comment]
Thanks! I can confirm this fixes the issue on Incendius for Alliance side.
