### ISSUE TITLE
Feature Request: Filtering

### ISSUE THREAD

**Issue by mcd8604** [kakysha/HonorSpy#68]
The standings are extremely skewed because many entries are very old. Would it be feasible to add the ability to filter out players based on fields such as LastSeen? It would be especially useful upon each week's reset, since the values are not resetting back to 0. Perhaps this is just a compound bug that could be handled by fixing a different bug. There are also several entries which have extremely high honor values, which should be ignored completely.

**Comment by kakysha** [comment]
You trying to fix a bug with strange solution. We already discussing what can we do about resets here https://github.com/kakysha/HonorSpy/issues/65
