### ISSUE TITLE
Decrease broadcast frequency

### ISSUE THREAD

**Issue by eliasbrange** [kakysha/HonorSpy#69]
Right now, every time a player dies they broadcast their entire table (given that 5 minutes has passed since last time). This is done in batches of 10 so for bigger servers where people easily have 4000+ people in their tables this results in 400+ messages sent every time a player dies. If 2000 of those people die within a 5 minutes span, that equals 800000 messages.

At least on Gehennas there has been severe chat issues the last week, which I'm going to take a wild guess has something to do with the wide usage of HonorSpy.

I'd suggest increasing this delay to one or two hours to reduce chat channel spam.

**Comment by kakysha** [comment]
Good point. This timeout was set when we were syncing across guild, but as we have server-wide syncing, it can be lowered.

**Comment by kakysha** [comment]
Done in v1.5.6
