### ISSUE TITLE
Feature Request: Tooltip Honor% Value

### ISSUE THREAD

**Issue by sasha-koss** [kakysha/HonorSpy#71]
Honor DR Tracker and HonorAssist have a tooltip display for how much % honor a target gives.
An Indicator if 100/75/50/25/0 would be nice, maybe going from Green to Red in color.

Tried using the addons in combination with HonorSpy, but they are replacing the honor message in a way that duplicates and spams the chat with 3-4 Honor messages per kill.

**Comment by kakysha** [comment]
Do you really need this feature? I mean, what would it change for you? Will you not kill a guy if he is yellow or red already?

**Comment by sasha-koss** [comment]
Its pretty useful in wpvp situation, i meet the same ppl all day.
In BGs like WSG its helpful for maxing honor as pre made group, you corps camp pugs and wait with the last flag until you grinded them 4 times.
But its pretty low prio because im using Honor DR Tracker and try to ignore the heavy chat spam.

**Comment by kakysha** [comment]
Won't implement it.
