### ISSUE TITLE
Honor Values broken

### ISSUE THREAD

**Issue by dagochen** [kakysha/HonorSpy#72]
On Lucifron the data from HonorSpy is completely broken now. We have several players with the exact same honor values and standings, wrong current ranks and so on. 

![image](https://user-images.githubusercontent.com/5236186/69916708-c272b480-145e-11ea-8489-c45f98514603.png)

**Comment by dagochen** [comment]
And the problem with the chat channels is back again too

**Comment by Nelythia** [comment]
Then tell the people to update the addon. The duplicate bug has been fixed ages ago.

**Comment by dagochen** [comment]
I think a newer version should ignore syncs from older versions.
