### ISSUE TITLE
Add honor/kills for yesterday and kills for today.

### ISSUE THREAD

**Issue by r0hitch0pra** [kakysha/HonorSpy#73]
I did this myself for saving the values but I'm terrible at understanding the gui. Should be a cake walk for you

**Comment by Nelythia** [comment]
What do you mean? The current version already has something like that in your honor tab.

**Comment by r0hitch0pra** [comment]
Not for yourself, the other players on the servers. The honor gained for the previous day along with HKs for the previous and the current day.

**Comment by kakysha** [comment]
Its impossible. You can't know how many honor did other player get during the day, its stored in his own addon only.

**Comment by r0hitch0pra** [comment]
Well I wasnt talking about honor for each day, just the HK's for each day. Just the count of the number of kills. That data is already returned GetInspectHonorData();

**Comment by kakysha** [comment]
Explain what do you want with screenshot pls. You talking about table? No, I won't add these columns to the table, as its already contains enough columns with some of them being "not very interesting", like LstWkHonor.

**Comment by r0hitch0pra** [comment]
The idea behind adding Honorable Kills for today is that it shows how active the player has been today. If the inspected report in the morning shows player JDoe had 40 kill but an inspect later shows he had 97. It would mean the player has been pvping all day. Similarly for Honor for the previous day. Just to compare what other players on the server got for the day before.
