### ISSUE TITLE
Chat channels moving, creating blank channels etc.

### ISSUE THREAD

**Issue by Larsy93** [kakysha/HonorSpy#75]
Every single time i login my General/Trade/World etc has changed their places, honorspy sync is all of a sudden on channel 1 + it appears like 2 blank channels aswell. I re-organize so that my general etc are at their correct place and next time I login they have changed again. Disabling honorspy addon removes the problem of channels hopping around and messing up the chat.
![a6b242c15d6262b28b418618e15fa8c1](https://user-images.githubusercontent.com/22322580/69960870-dbd13a80-150a-11ea-9da1-4ad319a2aa6d.png)

**Comment by Larsy93** [comment]
I am using version 1.5.6

**Comment by Larsy93** [comment]
Downloaded latest version 1.5.9 and problem is still the same 

![](https://i.gyazo.com/7af7b57d9418e02d3b7ea33c8724c7d9.png)

**Comment by kakysha** [comment]
Can you try to disable all other addons and see if it helps? Cause right now I wait 8 seconds before joining channels: `HS_wait(8, HS_joinSyncChannel)`, and 8 is more than enough for your game client to join /1 /2 /3 etc. channels. For me it looks like: I enter the world with all the /1 /2 /3 channels already set up, and after about 6-7 seconds (so, the loading takes ~1-2 seconds) addon joins its sync channel.
Its either 8 seconds is not enough for you, or the timer is broken. Try disabling all other addons and check.

**Comment by Larsy93** [comment]
Will do and report back with results

**Comment by Larsy93** [comment]
What about the 2 blank channels? They only appear with Honorspy enabled

**Comment by dagochen** [comment]
Maybe join sync channel when user clicks the minimap button? I need a lot more than 8 seconds to load the game cause of all my addons :D

**Comment by Larsy93** [comment]
Yeah changing the delay to like 30 seconds shouldnt be a problem imho, its not like u have to start syncing like a madman as soon as you login. Btw it only happens on my computer at work and that is an older slower computer, at home it doesnt switch the channels around, so it must be that my time to login is greater than 8 seconds when at work.

**Comment by kakysha** [comment]
It probably is, will increase the delay to 15 seconds.
Two blank channels made on purpose, so you can freely join new channels and still have numbers in order
