### ISSUE TITLE
HonorSpySync channel?

### ISSUE THREAD

**Issue by sMuve** [kakysha/HonorSpy#78]
Hey there,

a very active player always kick less active people from the HonorSpySync channel.
Do I have any consequences for being kicked from HonorSpySync channel?

Best regards
Smu

**Comment by kakysha** [comment]
New version (>=1.5.10) kicks everyone with older versions (prior to 1.5.6) that cause chat lags on the server. Upgrade to not be kicked and to not cause chat delays.
