### ISSUE TITLE
channelName as a setting

### ISSUE THREAD

**Issue by tresarwow** [kakysha/HonorSpy#79]
Seems like a lot of people are taking over the channel maliciously, kicking people out or simply injecting fake data.

Is it possible to be able to have the `channelName` as a setting rather than having it fixed to "HonorSpySync"?

**Comment by Nelythia** [comment]
The kicks are from the addon itself. As of 1.5.10 it kicks players with an older version from the channel to prevent old data & duplicate data being shared by those players that are too lazy to update the addon.
