### ISSUE TITLE
Feature Request: Last Week Standings

### ISSUE THREAD

**Issue by Phibs77** [kakysha/HonorSpy#80]
Hey Kaky, Zeeya from Nost PvE here *wave*

I was wondering if it would be possible to implement a "Last Week" tab into the HonorSpy Window to easily check last weeks standings, honor caps and brackets. Would be awesome!

Much love

Sorry if this has been requested already. :)

**Comment by kakysha** [comment]
Hey Zeeya!
Its already implemented. The standing column is, in fact, your previous week standing. You can sort by clicking on it. Its better to do it when your table is populated with most of users, so you not miss many standings.

**Comment by Phibs77** [comment]
Yes, but also no. I can sort it by last weeks standing but the bracket size is based on the current pool size, not on last week. For my purpose it would need to show last weeks bracket sizes according to the lowest standing achieved in the last week, like a completely new tab like the current window just with the data from last week instead of current week.

<3

**Comment by kakysha** [comment]
usually, addon doesnt have lowest standing player, as its usually low levels with minimum HKs which were not seen by anyone and done specifically to track pool size.
