### ISSUE TITLE
store_player: attempt to index local 'playerName' (a boolean value)

### ISSUE THREAD

**Issue by mcd8604** [kakysha/HonorSpy#81]
I'm not sure what I was doing when this occured, but I found it in Swatter so I figured posting it might help.

> Date: 2019-12-08 17:18:00
> ID: 38
> Error occured in: Global
> Count: 5
> Message: ..\AddOns\honorspy\honorspy.lua line 383:
>    attempt to index local 'playerName' (a boolean value)
> Debug:
>    honorspy\honorspy.lua:383: store_player()
>    honorspy\honorspy.lua:409: ?()
>    ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
>       ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
>    [C]: ?
>    ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
>       ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
>    ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
>    ...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:218: OnReceiveMultipartLast()
>    ...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:256:
>       ...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:246
> Locals:
> None
> AddOns:
>   Swatter, v8.2.6377 (SwimmingSeadragon)
>   WowheadLooter, v11302
>   AdvancedInterfaceOptions, v1.3.3
>   Atlas, vv1.45.01.11302
>   AtlasClassicWoW, vv1.45.00
>   AtlasLootClassic, vv1.3.4
>   AtlasLootClassicData, vv1.3.4
>   AtlasLootClassicDungeonsAndRaids, vv1.3.4
>   AucAdvanced, v8.2.6430 (SwimmingSeadragon)
>   AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
>   AucScanData, v8.2.6365 (SwimmingSeadragon)
>   AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
>   AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
>   AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
>   AucStatSimple, v8.2.6399 (SwimmingSeadragon)
>   AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
>   AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
>   BeanCounter, v8.2.6434 (SwimmingSeadragon)
>   CharacterStatsClassic, v2.6
>   ClassicAuraDurations, v
>   ClassicCastbars, vv1.1.5
>   ClassicCastbarsOptions, v
>   CTBarMod, v8.2.5.5
>   CTBottomBar, v8.2.5.5
>   CTBuffMod, v8.2.5.5
>   CTCore, v8.2.5.5
>   CTExpenseHistory, v8.2.0.1
>   CTLibrary, v8.2.5.5
>   DBMCore, v1.13.20
>   DBMDefaultSkin, v
>   DBMStatusBarTimers, v
>   Details, v
>   DetailsStreamer, v
>   DetailsTinyThreat, v
>   Enchantrix, v8.2.6428 (SwimmingSeadragon)
>   EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
>   ExtendedCharacterStats, v1.5
>   FarmLog, vv1.6
>   GatherMate2, v1.45.5
>   GuildRosterManager, v1.831
>   HonorAssist, v0.5
>   honorspy, v1.5.11
>   Informant, v8.2.6374 (SwimmingSeadragon)
>   ItemRack, v
>   LeatrixMaps, v1.13.36
>   LeatrixPlus, v1.13.37
>   MonolithDKP, v1.6.2
>   NameplateCooldowns, v
>   NugEnergy, v1.13.11
>   OmniBar, vv10.6
>   OmniCC, v8.2.5
>   OPie, vAncient Walnut 5
>   Puggle, v2.6
>   Quartz, v3.5-classic-5
>   Questie, v5.2.2 1 a6c8207
>   SheepMonitor, v1.22
>   SlideBar, v8.2.6375 (SwimmingSeadragon)
>   Spy, v1.0.14
>   Stubby, v8.2.6376 (SwimmingSeadragon)
>   WeakAuras, v2.15.5
>   ZPerl, v5.8.7
>   ZPerlArcaneBar, v
>   ZPerlParty, v
>   ZPerlPartyPet, v
>   ZPerlPlayer, v
>   ZPerlPlayerBuffs, v
>   ZPerlPlayerPet, v
>   ZPerlRaidAdmin, v
>   ZPerlRaidFrames, v
>   ZPerlRaidHelper, v
>   ZPerlRaidMonitor, v
>   ZPerlRaidPets, v
>   ZPerlTarget, v
>   ZPerlTargetTarget, v
>   BlizRuntimeLib_enUS v1.13.2.11302 <none>
>   (ck=829)
> 
>

**Comment by kakysha** [comment]
fixed in 1.5.12
