### ISSUE TITLE
Upcoming patch will break honorspy

### ISSUE THREAD

**Issue by sbrkopac** [kakysha/HonorSpy#82]
> With the release of World of Warcraft Classic 1.13.3 9, we’re making a change to disallow calling C_ChatInfo.SendAddonMessage with the CHANNEL ChatType. This will prevent addons from communicating over custom, player-created chat channels. 

Not sure how to work around it but figured I'd open a ticket.

**Comment by kakysha** [comment]
It won't break it in any way, cause syncing still works using /guild, /raid, /bg and /party channels.
I just removed HonorSpySync channel completely in v1.6.0, update pls.
