### ISSUE TITLE
PRO IDEA Fix Realm~~~ READ

### ISSUE THREAD

**Issue by Rootkit-** [kakysha/HonorSpy#85]
Create a purge of local data and sync data only with people who have the newer version. You should really implement current version or higher sync condition to check.

**Comment by ATeal** [comment]
Came here to mention similar issue -- After update looks like data is still wrong even after reset. Seems to have sync'd bad data

**Comment by kakysha** [comment]
done

**Comment by ATeal** [comment]
Just wanted to come by and drop a TY :)
