### ISSUE TITLE
"You are not in a raid group." message in battleground (v1.6.7 classic)

### ISSUE THREAD

**Issue by jeichenhofer** [kakysha/HonorSpy#88]
Every time someone joins the battleground instance, this message appears in the chat log. I'm assuming it has something to do with the announcement mechanism of this addon.

**Comment by kakysha** [comment]
you assuming it wrong

**Comment by ghost** [comment]
I am also getting these messages about every ~10 seconds while in battlegrounds. If I disable honorspy the spam heavily reduces (probably some other addon having the same issue). Running version 1.6.7 too.

Edit: only on entering bg now, spam was with 1.6.6
