### ISSUE TITLE
Enhancement Request: Use estimated honor values for the table

### ISSUE THREAD

**Issue by crist074** [kakysha/HonorSpy#90]
When an honorspy user updates their estimated honor, use that data to broadcast to the table and ignore 3rd person inspection data. This would allow us to better estimate which bracket we would end up in as most of the higher bracket players use this addon.

**Comment by kakysha** [comment]
It will estimate nonsense, because only HonorSpy users will have their estimated honor, and others will have the honor to the start of the day

**Comment by crist074** [comment]
What do you mean it will estimate nonsense? If everyone in brackets 14-10 have honorspy, and all honor estimates are being tracked correctly, each player in those brackets should be able to see how they stand in terms of honor during the day. For example, I chat with the other people in my guild to determine how much honor they have for the day and compare it to my own estimated values.

**Comment by kakysha** [comment]
key point is "If everyone in brackets 14-10 have honorspy", which is not true and never will be.  And for top brackets even one guy without addon can screw things up for the rest.
