### ISSUE TITLE
作者你好！

### ISSUE THREAD

**Issue by tzn521** [kakysha/HonorSpy#92]
我是你插件的忠实粉丝！
问题是，如何设置更新日期呢？亚洲 数据更新日期与美服不同，希望能告知如何设置，我的英文不好，只能通过翻译软件告诉你，谢谢！或者希望能够单独调整下亚服的更新时间，做一个亚服专版，谢谢啦！
非常感谢你的插件！

I'm a big fan of your plugins!
The question is, how do I set the update date? The update date of Asian data is different from that of USV. I hope to tell you how to set it. My English is not good. I can only tell you through translation software. Thank you! Or I hope that I can adjust the update time of inferior service independently and make a special edition of inferior service. Thank you!
Thank you so much for your plug-in!

**Comment by kakysha** [comment]
Just tell me the correct time and your region / server?

**Comment by imoldchen** [comment]
US (includes Brazil and Oceania) - 8 AM PST / 10 AM EST / 3 PM UTC
EU - 8 AM CET / 7 AM UTC
China - 7 AM CST / 8AM UTC

**Comment by tzn521** [comment]
是的，中国时间 每周二上午7点。能否调整下谢谢啦！
Yes, it's 7 a.m. Chinese time every Tuesday. Can you adjust it? Thank you!

**Comment by kakysha** [comment]
someone told me its 7 AM KST Thursday.
You sure its Tuesday?

**Comment by tzn521** [comment]
是的，中国是每周二更新军衔经验以及排名。周4 是中国服务器维护的常用时间，而不是军衔的更新时间。而且是北京时间。。没有夏令时，具体换算应该是UT+8 ？

**Comment by tzn521** [comment]
Yes, China is updating its rank experience and ranking every Tuesday. Thursday is a common time for server maintenance in China, not for rank updates. And it's Beijing time.. Without daylight saving time, it should be ut + 8?

**Comment by tzn521** [comment]
![image](https://user-images.githubusercontent.com/42259435/71387507-2d16aa80-262f-11ea-95db-1eb15f989692.png)

不知是否能看见图。据游戏内GM回复，周二上午7点更新，但因为中国玩家数据过大，有些人是没有同步更新完成的，会晚，但也是在周三前更新完。如果数据不大，理论上周二早上7点就是军衔的更新日期。

I wonder if I can see the picture. According to the in game GM, it was updated at 7:00 on Tuesday morning, but because the data of Chinese players is too large, some people didn't complete the synchronous update, which will be late, but also before Wednesday. If the data is not large, in theory, 7 a.m. on Tuesday is the update date of military rank.

**Comment by tzn521** [comment]
[https://github.com/tzn521/tzn521.github.io/blob/master/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_1577151018743.png](url)

**Comment by kakysha** [comment]
Ok, thank you. I changed it to Tuesday instead of Thursday. Will be in the next release.
