### ISSUE TITLE
Standings Pool filled w Characters from Other Realms

### ISSUE THREAD

**Issue by emiliodacosta** [kakysha/HonorSpy#94]
I am on Skeram-Horde and the HonorSpy Standings is showing that my pool size is currently 5832. There are lots of chars in the list for which my Last Seen time is 4d, 5d, 6d, etc... and so they are showing their honor values for last week and yet being ranked for this week and this is totally screwing up the Standings. I tried uninstalling and reinstalling but it didn't seem to help. IIs there a way I can reset my HonorSpy database?

 I believe the issue is related to the pool having chars from other realms because my friends in this realm that seem to have a properly functioning HonorSpy all have much, much smaller pool sizes.

**Comment by Godmatik** [comment]
Update to the latest HonorSpy version (1.6.7) and purge your data, your list won't populate with cross-realm names any further.

**Comment by emiliodacosta** [comment]
I've been on the latest version. How do I "purge my data"?

**Comment by emiliodacosta** [comment]
Delete my honorspy.lua file from WTF/Account/<accountname>/SavedVariables/ ???

**Comment by emiliodacosta** [comment]
I tried deleting the .lua file but that did not seem to have any impact... any suggestions?

**Comment by tzn521** [comment]
在导出csv 文件旁边有个 清除数据。。

**Comment by kakysha** [comment]
You don't need to purge anything. If you are on latest version, it will purge automatically for you, also you should not receive prev. week data.
Can you double check that you use the latest version from curseforge and that you have those x-realm guys? Provide a screenshot, if possible.

**Comment by emiliodacosta** [comment]
![BojaroSkeram_HonorSpyStandings](https://user-images.githubusercontent.com/27406699/71386369-68779180-25bb-11ea-895c-79f18c01a3a1.PNG)

**Comment by emiliodacosta** [comment]
Fusbread and Airan should not be in the list - the honor value they are showing for them is from the previous week (Last Seen 8d). Those are two of the ones that I have that I assume are from another realm. There used to be a lot more but many of the problematic ones have been slowly disappearing as the week goes on.

**Comment by kakysha** [comment]
Did you transfer to another server during this week?

**Comment by emiliodacosta** [comment]
No I did not engage in any server transfers - perhaps those other players did?

**Comment by kakysha** [comment]
Ok, I have no ideas left why that happened, but its the reset problem. I will include week reset call on data purge, as a temporary solution. Though, next week should be fine for you automatically even whithout this fix.

**Comment by emiliodacosta** [comment]
everything seems to be working fine now - thank you for your assistance
