### ISSUE TITLE
Feature request : Last week honorable kill count

### ISSUE THREAD

**Issue by rgalan89** [kakysha/HonorSpy#96]
Hello.

As the addon extract and shows in the GUI the Last Week honor count , its possible to also show the honorable kill count? We are suffering a huge wave of ppl afking in BGs , having a huge amount of honor but really little or 0 honorable kills.

This could greatly help the community identify and report those scumbag players.

**Comment by kakysha** [comment]
No, this is useless info for the majority of ppl.
