### ISSUE TITLE
Data not syncing passively

### ISSUE THREAD

**Issue by wentsa** [kakysha/HonorSpy#99]
I use HS 1.6.7. and I have completely empty table. I have visited multiple BGs and I am in guild so I should have the data synced passively by these channels but it is not. The only way some data get to my list is by inspecting player and clicking on their honor tab. This is the only way I have found to get them into my data.

I am playing on Horde - Judgement (Karthay).

this is my CSV data:

Zeil,WARRIOR,76285,366082,21,35157,9,12/26/19 21:04:35,
Rademer,SHAMAN,57375,288876,30,30451,8,12/26/19 21:08:57,
Tuutsa,HUNTER,29385,112361,110,12550,4,12/26/19 20:49:22,
Karthay,WARLOCK,11823,32459,249,10334,4,12/26/19 21:16:23,

**Comment by kakysha** [comment]
Can't reproduce, is it still the case?

**Comment by wentsa** [comment]
It's working OK now (1.7.1) - closing
